language: python

after_success:
    - bash <(curl -s https://codecov.io/bash)

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

# install dependencies
install:
    - python -m pip install --upgrade pip
    - pip install -U importlib_metadata # for python 3.7 compatibility (see https://travis-ci.community/t/build-error-for-python-3-7-on-two-different-projects/12895/2)
    - pip install -r requirements.txt

# run unitttest
script:
    - python test/extracellular_unittest.py
